# Generated by Django 4.2.7 on 2023-11-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='costo_diario',
            field=models.PositiveIntegerField(),
        ),
    ]
